name: automerge
on: 
  status: {}
  pull_request:
    types: [labeled synchronize]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep first
        run: sleep 301
      - name: automerge
        uses: "pascalgn/automerge-action@v0.7.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_ACTIONS }}"
          MERGE_METHOD: "squash"
          MERGE_FORKS: "false"
          UPDATE_METHOD: "rebase"
