name: automerge
on: 
  status: 
  check_run: 
  check_suite: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "* * * * *"
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.7.4"
        run: sleep 300
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_ACTIONS }}"
          MERGE_METHOD: "squash"
          MERGE_FORKS: "false"
          UPDATE_METHOD: "rebase"
